### ISSUE TITLE
Loosen restriction of variable description (string) length beyond 128 characters

### ISSUE THREAD

**Issue by rsgoncalves** [cjendres1/nhanes#10]
Great work on this package—super helpful!

It looks like there is a restriction on the character length of variable descriptions obtained via the `nhanesTableVars()` function: https://github.com/cjendres1/nhanes/blob/92cb25625502729282cea3131728f5f4a4af10c4/R/nhanes.R#L332

Would it be possible to not hard-code the restriction to 128 characters so that we can obtain the full descriptions?

**Comment by cjendres1** [comment]
Thanks for using nhanesA! Glad you find it useful.
Out of curiosity, are you interested in the full string because you would like to view it or do you anticipate using it for analytic purposes (e.g. text mining)? Would appreciate if you can send me examples of strings that get cut off. Then I can test and make sure I relax the restriction enough.

**Comment by cjendres1** [comment]
I increased the allowable size to 1024 and I set defaults to 128 across the board.
Please install from my git repo:
install_github("cjendres1/nhanes")

The installation will show up as nhanesA 0.7.1

**Comment by cjendres1** [comment]
Fix added to nhanesA 0.7.1 which is now on CRAN
