### ISSUE TITLE
Functionality to obtain `SAS Label` of each variable

### ISSUE THREAD

**Issue by rsgoncalves** [cjendres1/nhanes#11]
Would it be possible to obtain the SAS Label of each variable, to facilitate analysis/post-processing of study variables?

For example, to have all the following details of each variable:

> **Variable Name:** DRDINT
> **SAS Label**: Number of days of intake
> **English Text:** Indicates whether the sample person has intake data for one or two days.

**Comment by cjendres1** [comment]
Most straightforward way would be to modify nhanesTranslate to return those fields.
I'll take a look
Thanks

**Comment by cjendres1** [comment]
[nhanesCodebook.txt](https://github.com/cjendres1/nhanes/files/9428504/nhanesCodebook.txt)

Please rename the attached file to nhanesCodebook.R 
For some reason it doesn't allow attaching '.R' files
In your R session
1: source('nhanesCodebook.R')
2: nhanesCodebook('AUX_D', 'AUQ020D')

Let me know if the result of the last command is what you're looking for. It's a list since there's a mixture of data types.
Please test it out as much you can and let me know if there's any unexpected behavior.
Thanks!

**Comment by rsgoncalves** [comment]
Thank you for the prompt response and resolution!  The `nhanesCodebook.R` (and `nhanesCodebook` function) are exactly what is desired. After some basic tests things look good to me. Thanks!

**Comment by cjendres1** [comment]
Fix added to nhanesA 0.7.1 which is now on CRAN
